# Import model here
# model.load()

# Pass the Model Story Prompt(s)
# From List of ideas --> [prompt.txt]

# Output json to data: Example Format
# {
#     "title": "STORY TITLE",
#     "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum tempor vulputate. Quisque euismod laoreet ultrices. Ut nec sem ultricies, blandit purus sit amet, gravida arcu. Donec id sodales nisi, a blandit purus. Morbi ullamcorper venenatis augue rutrum tincidunt. Fusce aliquam libero luctus dignissim viverra. Quisque risus ipsum, euismod sit amet orci ut, maximus molestie nibh. Suspendisse potenti. Vivamus laoreet sem consectetur volutpat eleifend. Sed justo metus, elementum eu lobortis vitae, sollicitudin feugiat libero. Nullam turpis leo, ultrices non aliquet malesuada, dictum et ante. Nulla ultricies pellentesque purus, sed rutrum enim eleifend sit amet. Nunc sed risus pellentesque, sollicitudin quam id, facilisis eros. Praesent semper scelerisque metus, in mollis ligula. Sed luctus erat scelerisque, rutrum nunc pulvinar, finibus risus. Sed eu viverra enim, in auctor metus. Quisque egestas neque nisi, eget eleifend metus volutpat non. Ut massa diam, dapibus a sapien ac, blandit volutpat eros. Quisque ut enim ut ante ornare lobortis at a nisl. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus iaculis velit vestibulum dolor commodo finibus. Fusce laoreet lacinia eros eget iaculis. Nullam sagittis leo nibh. Aliquam sollicitudin, nisl ut lobortis blandit, nisl est scelerisque ante, non ultrices risus elit sed felis. Praesent vitae felis et erat tincidunt interdum nec bibendum enim. Suspendisse dignissim consectetur ipsum ac luctus. Donec gravida dictum velit, dapibus semper magna ullamcorper quis. Suspendisse sagittis erat quis sagittis rutrum. Suspendisse nec orci ut odio vehicula consequat et sed mi. Maecenas sit amet sapien id velit porta molestie. Quisque a ante nibh. Aliquam vitae nibh efficitur, tincidunt sem ac, aliquam quam. Aenean laoreet aliquet augue, id ornare ante gravida eu. Proin egestas, tortor ac ultrices ullamcorper, erat enim fermentum urna, vel scelerisque purus nibh ac turpis. Curabitur blandit tempor pretium. Sed in diam interdum, scelerisque lacus eget, elementum ex. Phasellus quis tortor nec ante ultrices mattis nec sit amet dolor. Integer ut felis et leo congue blandit. Phasellus magna nisl, congue at pharetra vel, ultrices quis nisl. Proin cursus enim a ipsum fringilla, quis consectetur mauris imperdiet. Aliquam vulputate ligula et augue semper efficitur at sit amet massa. Sed egestas tincidunt velit. Donec fermentum, orci nec ultrices facilisis, augue justo blandit tellus, eu rutrum nulla mi in est.",
#     "author": "Esmé de La Rêverie",
#     "render_count": 0
# }
